### ISSUE TITLE
Как правильно задать директорию на output

### ISSUE THREAD

**Issue by alexTitakov** [tonchik-tm/pdf-to-html#3]
Здравствуй Тончик!.

крутая штука, только я в php очень нуб, особенно в ООП.
Неопдскажешь как именно задавать директорию на output html  страниц?...
по настройкам "/tmp"..Но там пусто.

рад буду ответу, а особенно если он будет до здачи проекта...;))

**Comment by tonchik-tm** [comment]
Приветствую!
В настройках есть три параметра для директории вывода:
'clearAfter' => true, // автоматическая очистка после разбора
'removeOutputDir' => true, // удалят саму output dir после разбора
'outputDir' => '/tmp/'.uniqid(), // output dir

соответственно, если 'clearAfter' = false, то файлы все останутся

**Comment by alexTitakov** [comment]
Благодарю за оперативность...:)

запустил ваш движочек, правда через бинарники Gufi. вроде все хорошо
[anysites](http://profsouz.ad-rus.com/admin/test/analitics.php).

Я так же и  изменял вроде бы настройки, но что-то не ничгео происходило
Прошу прощения за свою **"одупленность" в Php,** но где правильно вставить блок Settings?)
Есть страница, на ней выполняется весь код. У меня Settings стояли после кода как в документации

...;)
спасибо что уделили время

**Comment by tonchik-tm** [comment]
```
$pdf = new \TonchikTm\PdfToHtml\Pdf('test.pdf', [
    'pdftohtml_path' => '/usr/bin/pdftohtml',
    'pdfinfo_path' => '/usr/bin/pdfinfo'
]);
```
Здесь как раз и устанавливаются настройки, просто все остальные в данном случае по-умолчанию остаются.

Т.е. Вам нужно примерно так:
```
$pdf = new \TonchikTm\PdfToHtml\Pdf('test.pdf', [
    'pdftohtml_path' => '/usr/bin/pdftohtml',
    'pdfinfo_path' => '/usr/bin/pdfinfo',
    'outputDir' => '/tmp/'.uniqid(),
    'clearAfter' => false,
]);
```

**Comment by alexTitakov** [comment]
;)....блин, вот снубил.
буду знать.

спасибо!
успехов в разработке!
